In [1]:
import pandas as pd
import numpy as np

## Worklist prioritization: Emergency Setting

In [2]:
## First, read in the file of the current worklist with the probabilities that your two algorithms have
## generated for the two types of findings you're most concerned with:

worklist = pd.read_csv('probabilities.csv')

In [4]:
worklist.head(10)

   Image_Type  Brain_bleed_probability  Aortic_dissection_probability
0  chest_xray                     0.00                           0.05
1  chest_xray                     0.00                           0.17
2  chest_xray                     0.00                           0.00
3  chest_xray                     0.00                           0.04
4  wrist_xray                     0.00                           0.00
5  chest_xray                     0.00                           0.67
6  femur_xray                     0.00                           0.00
7  femur_xray                     0.00                           0.00
8  wrist_xray                     0.00                           0.00
9     head_ct                     0.13                           0.00

In [5]:
worklist['time'] = worklist.index*6

In [6]:
worklist.head(10)

   Image_Type  Brain_bleed_probability  Aortic_dissection_probability  time
0  chest_xray                     0.00                           0.05     0
1  chest_xray                     0.00                           0.17     6
2  chest_xray                     0.00                           0.00    12
3  chest_xray                     0.00                           0.04    18
4  wrist_xray                     0.00                           0.00    24
5  chest_xray                     0.00                           0.67    30
6  femur_xray                     0.00                           0.00    36
7  femur_xray                     0.00                           0.00    42
8  wrist_xray                     0.00                           0.00    48
9     head_ct                     0.13                           0.00    54

In [18]:
def calculate_priority(row):
    if row['Brain_bleed_probability'] > 0 and row['Brain_bleed_probability'] <= 0.3 :
        return 1
    if row['Brain_bleed_probability'] > 0.3 and row['Brain_bleed_probability'] <= 0.6 :
        return 2
    if row['Brain_bleed_probability'] > 0.6 :
        return 3
    if row['Aortic_dissection_probability'] > 0 and row['Aortic_dissection_probability'] <= 0.3 :
        return 1
    if row['Aortic_dissection_probability'] > 0.3 and row['Aortic_dissection_probability'] <= 0.6 :
        return 2
    if row['Aortic_dissection_probability'] > 0.6 :
        return 3
    else :
        return 0
    
def calculate_probability(row):
    return max(row['Brain_bleed_probability'], row['Aortic_dissection_probability'])

In [19]:
worklist['priority'] = worklist.apply(lambda row: calculate_priority(row), axis=1)
worklist['probability'] = worklist.apply(lambda row: calculate_probability(row), axis=1)
worklist.head(10)

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time,priority,probability
0,chest_xray,0.00,0.84,288,3,0.84
1,chest_xray,0.00,0.83,228,3,0.83
2,chest_xray,0.00,0.67,30,3,0.67
3,chest_xray,0.00,0.95,90,3,0.95
4,head_ct,0.91,0.00,504,3,0.91
5,head_ct,0.78,0.00,534,3,0.78
6,chest_xray,0.00,0.94,60,3,0.94
7,chest_xray,0.00,0.93,282,3,0.93
8,chest_xray,0.00,0.82,522,3,0.82
9,chest_xray,0.00,0.79,510,3,0.79

In [20]:
worklist = worklist.sort_values('probability', ascending=False, ignore_index=True)
worklist

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time,priority,probability
0,head_ct,0.99,0.00,150,3,0.99
1,chest_xray,0.00,0.95,90,3,0.95
2,chest_xray,0.00,0.94,60,3,0.94
3,chest_xray,0.00,0.93,450,3,0.93
4,chest_xray,0.00,0.93,282,3,0.93
...,...,...,...,...,...,...
94,wrist_xray,0.00,0.00,210,0,0.00
95,chest_xray,0.00,0.00,402,0,0.00
96,femur_xray,0.00,0.00,312,0,0.00
97,femur_xray,0.00,0.00,192,0,0.00
98,chest_xray,0.00,0.00,588,0,0.00

In [21]:
worklist['new_time'] = worklist.index*6
worklist

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time,priority,probability,new_time
0,head_ct,0.99,0.00,150,3,0.99,0
1,chest_xray,0.00,0.95,90,3,0.95,6
2,chest_xray,0.00,0.94,60,3,0.94,12
3,chest_xray,0.00,0.93,450,3,0.93,18
4,chest_xray,0.00,0.93,282,3,0.93,24
...,...,...,...,...,...,...,...
94,wrist_xray,0.00,0.00,210,0,0.00,564
95,chest_xray,0.00,0.00,402,0,0.00,570
96,femur_xray,0.00,0.00,312,0,0.00,576
97,femur_xray,0.00,0.00,192,0,0.00,582
98,chest_xray,0.00,0.00,588,0,0.00,588

In [23]:
worklist['diff_time'] = worklist['time'] - worklist['new_time']

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time,priority,probability,new_time,diff_time
0,head_ct,0.99,0.00,150,3,0.99,0,150
1,chest_xray,0.00,0.95,90,3,0.95,6,84
2,chest_xray,0.00,0.94,60,3,0.94,12,48
3,chest_xray,0.00,0.93,450,3,0.93,18,432
4,chest_xray,0.00,0.93,282,3,0.93,24,258
...,...,...,...,...,...,...,...,...
94,wrist_xray,0.00,0.00,210,0,0.00,564,-354
95,chest_xray,0.00,0.00,402,0,0.00,570,-168
96,femur_xray,0.00,0.00,312,0,0.00,576,-264
97,femur_xray,0.00,0.00,192,0,0.00,582,-390
98,chest_xray,0.00,0.00,588,0,0.00,588,0

In [24]:
worklist

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time,priority,probability,new_time,diff_time
0,head_ct,0.99,0.00,150,3,0.99,0,150
1,chest_xray,0.00,0.95,90,3,0.95,6,84
2,chest_xray,0.00,0.94,60,3,0.94,12,48
3,chest_xray,0.00,0.93,450,3,0.93,18,432
4,chest_xray,0.00,0.93,282,3,0.93,24,258
...,...,...,...,...,...,...,...,...
94,wrist_xray,0.00,0.00,210,0,0.00,564,-354
95,chest_xray,0.00,0.00,402,0,0.00,570,-168
96,femur_xray,0.00,0.00,312,0,0.00,576,-264
97,femur_xray,0.00,0.00,192,0,0.00,582,-390
98,chest_xray,0.00,0.00,588,0,0.00,588,0